### PR TITLE
Adding features to Group class

### PR DESCRIPTION
**Pull request by Ameyanagi**
@newville 
I am working on adding a feature to the Group class that allows iteration and getting attributes in a similar manner as a dictionary.

Please look at the notebook attached for an example of how it helps to work on multiple spectra.
examples/Jupyter/Iteration_of_Group.ipynb

I believe this will provide a simple and straightforward way of dealing with multiple spectra. (for example, dealing with Athena project files.)

Since I don't think I have permission to make a new branch, can you add a branch to test these features?

I will also open an issue to discuss how it should be dealt with.

### CODE REVIEW

**Review by newville — COMMENTED** [review]
Thanks -- I think this looks good.  I don't think the `isinstance(key, int)` is that useful:  the dictionary of `__dir__()` will be ordered so access by index could work, but only if you know the order of the keys, in which case why not just use the appropriate key? 
Do you think it is necessary to have this index access?  To be clear, attribute names (so `keys in __dir__()` cannot be (or even start with) integers.  I think there is no chance of confusion, just no intrinsic meaning to the order.   Or maybe: it's very useful that the order of the dictionary keys is preserved, but it's not very useful what that actual order is.

I also think that if `Group` gets these methods, then it is not necessary for downstream subclasses to explicitly add those.   Indeed, `AthenaGroup` might be able to drop its `to_dict()` method, but I wouldn't necessarily suggest that be removed until it goes through a deprecation step (and maybe just reimplement `to_dict()` would be better anyway).

**Comment by Ameyanagi** [comment]
@newville 
I implemented access with an index because I thought it would be helpful for those who are familiar with pandas, where the data can be accessed either by index or the key.
I find it useful, but it will be a potential cause of bugs, and I agree that it might not be needed. 

I personally like using pandas, and sometimes I want to access with an index instead of keys, for example, when I want to plot matplotlib with specific cmap numbers. However, this can be done easily with enumerate, and it might not be necessary. I think it can be removed. 

I agree with dropping to_dict() in the future through the deprecation step, but at the current moment, I am not sure how much of the code is used in the whole Larch package.

Thank you for the suggestion, I will delete the index access later.

**Comment by newville** [comment]
@Ameyanagi Do you think we should merge and then modify or modify before merging?

**Comment by Ameyanagi** [comment]
@newville 
Hi Sorry for late reply, I was busy this 2 weeks. I just modified the Groups so that integer indexing is not allowed.
I raised an error when trying to index through a integer, to show that integer indexing is explicitly disabled.

The functionality shown in the example notebooks were checked.

**Comment by newville** [comment]
@Ameyanagi Thanks!  I'll happily merge this and will be fascinated to see how long it takes for me to get used to it and then not be able to live without it ;)

**Pull request merged**
