### PR TITLE
XasDataSource: common API to XAS data

### LINKED ISSUE #409: Support for SOLEIL NeXus file format
The file format used in the two beamlines I've been to at SOLEIL is [NeXus](https://www.nexusformat.org/), which is HDF5 under the hood. The files can, thus, be opened using larch.io.h5group on the command line, but XAS Viewer still refuses to open it with the following traceback:

```
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : 'measurement' not found -> use 'set_scan' method first
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : object of type 'NoneType' has no len()
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : 'measurement' not found -> use 'set_scan' method first
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : object of type 'NoneType' has no len()
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : 'measurement' not found -> use 'set_scan' method first
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : object of type 'NoneType' has no len()
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : 'measurement' not found -> use 'set_scan' method first
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : 'instrument/positioners' not found -> use 'set_scan' method first
[larch.io.specfile_reader.DataSourceSpecH5] ERROR : 'measurement' not found -> use 'set_scan' method first
Traceback (most recent call last):
  File "/home/kaarel/Develop/xraylarch/larch/wxxas/xasgui.py", line 1152, in onReadDialog
    self.onRead(path)
  File "/home/kaarel/Develop/xraylarch/larch/wxxas/xasgui.py", line 1167, in onRead
    self.show_subframe('spec_import', SpecfileImporter,
  File "/home/kaarel/Develop/xraylarch/larch/wxxas/xasgui.py", line 1105, in show_subframe
    self.subframes[name] = frameclass(self, **opts)
  File "/home/kaarel/Develop/xraylarch/larch/wxlib/specfile_importer.py", line 341, in __init__
    self.curscan = self.specfile.get_scan(curscan)
  File "/home/kaarel/Develop/xraylarch/larch/io/specfile_reader.py", line 703, in get_scan
    motor_names = self.get_scan_motors()
  File "/home/kaarel/Develop/xraylarch/larch/io/specfile_reader.py", line 514, in get_scan_motors
    return [i for i in counters if i in all_motors]
TypeError: 'NoneType' object is not iterable
```

The .nxs file in question is from the PUMA beamline at SOLEIL, and is provided as an attachment.

Aside from allowing to load the SOLEIL .nxs files in XAS viewer, it would be nice to provide a more convenient access function on the command line interface. For example, to get fluorescence data out of the attached file, you would need to go rather deep into the hierarchy of the created Group:

```
from larch import Interpreter
from larch.io import h5group

_larch = Interpreter()
h5 = h5group("ALARA401_JV07-map1-spot1-0063.nxs", _larch)
h5.exp.scan_data.data_01
```

Since most of the other innumerable streams of data in these .nxs files seem to be sample and instrumentation metadata, it might make sense for this convenience function to attach the contents of `h5.exp.scan_data` to the root of the Group, as these are the data most relevant to XAFS analysis in practice. Perhaps the [`NXData` identifier](https://manual.nexusformat.org/introduction.html#important-classes) can be used to push up the relevant data further in the hierarchy.

[ALARA401_JV07-map1-spot1-0063.zip](https://github.com/xraypy/xraylarch/files/9648590/ALARA401_JV07-map1-spot1-0063.zip)

### PR DESCRIPTION
**Pull request by woutdenolf**
Closes #409

To check with the data from https://github.com/xraypy/xraylarch/issues/409#issuecomment-1259174550

```python
from glob import glob
from larch.io.xas_data_source import open_xas_source

for filename in glob("*.nxs"):
    source = open_xas_source(filename)
    print()
    print(filename)
    print(source.TYPE)
    for name in source.get_scan_names():
        scan = source.get_scan(name)
        print(scan.name)
        print(scan.description)
        print(scan.labels)
```

This API works with all NeXus compliant HDF5 files (extra support for ESRF and SOLEIL) and SPEC files.

Unit tests are provided for HDF5 (ESRF, SOLEIL, generic NeXus) and SPEC files.

GUI support has been started but needs work in another PR.

### CODE REVIEW

**Comment by woutdenolf** [comment]
@newville Does this go in the right direction? Do you think the API would work for all other sources (athena, xdi, ...)? It would be nice if all data importers have the same API.

**Comment by maurov** [comment]
@woutdenolf @newville what should we do with this pull request?

Here what I propose:
- keep the code in `xas_data_source`
- discard all GUI related changes in `wxlib` and `wxxas`
- convert `test.py` to a Jupyter notebook example to put in `examples/Jupyter`

**Comment by newville** [comment]
@woutdenolf @maurov  Yeah, sorry that this got side-lined and less attention than it should have gotten.  

I agree with the idea, and having a folder/module for `xas_data_source` (maybe `io.xas`?? not a strong preference) is a generally good idea -- like, we could move the existing readers for Athena and XDI, and perhaps beamline-specific readers (but hopefully not too maybe "facility-specific" readers) there as well, and then potentially have a folder/module for readers of XES, XRF, XRD, XRF map data too.  

So, I agree with Mauro that we take `xas_data_source` and then re-work the changes to `wxlib` and `wxxas`.  And, yes to a Jupyter example!

I'm OK with merging this even if not quite finished, and then fixing up some of those things in follow-up work.

**Comment by woutdenolf** [comment]
@newville Do you mind waiting over the holidays. I will likely find some time to work on this.

**Comment by newville** [comment]
@woutdenolf  Yes, that is no problem at all!

**Comment by maurov** [comment]
@newville @woutdenolf thanks for your feedback! OK, let's wait new year for working on this (in parallel with the NXxas definition). 

We currently have three different APIs for reading Spec/HDF5/NeXus (ESRF) spectroscopy data:
- this proposal
- what I have done in `larch.io.datasource_spech5` (wrapper on top of `silx.io.open`)
- [DAXS](https://gitlab.esrf.fr/spectroscopy/daxs)

It would be great to merge everything in a single common API, @mretegan would you be interested in merging here what you have done in DAXS?

@newville @woutdenolf @mretegan, what about to postpone this to a **code camp** during the ESRF users meeting week in February? It would be much faster than discussing here.

**Comment by newville** [comment]
@maurov @woutdenolf @mretegan   I am OK for a code camp at/around the ESRF user meeting.  

I would say that 3 different opinions/codes from 3 different people for reading ESRF Spec/HDF5 files is understandable ;).  But hopefully, those could be combined.  

FWIW, my preference is usually to avoid too many "Factory functions" and "abstract reader classes" and try to keep things as pretty simple functions when possible.  But for a complex data store like an HDF5 file, a class that wraps the file and has methods to get/set/manipulate various data bits from that does make sense.

**Comment by woutdenolf** [comment]
@newville @maurov Ready for review/merge. I added unit tests and removed the GUI support (code is commented).

**Comment by maurov** [comment]
@woutdenolf @newville I have done some quick tests on my side and I propose merging it.

**Comment by newville** [comment]
@maurov @woutdenolf OK, I'll merge this... thanks both!

**Pull request merged**
