### PR TITLE
Read specfile in xas_viewer

### PR DESCRIPTION
**Pull request by maurov**
@newville This pull request for having Spec files read as Larch groups:

- [X] refactor `larch.io.specfile_reader` with the HDF5-like API to Spec files (via `silx.io.open`)
- [X] add `read_specfile` function that mimics the behaviour of `read_xdi`

### CODE REVIEW

**Comment by newville** [comment]
@maurov I think this would be great!  I'll look at the problem with the file. I'm also thinking that an h5 reader (basically, browsing for 1-d data) would be really helpful...

**Comment by newville** [comment]
@maurov  Is this ready to merge?  I was looking at this and #278, and I think it would help (me anyway) if this was merged -- Is that OK with you?

**Comment by maurov** [comment]
> 
> 
> @maurov Is this ready to merge? I was looking at this and #278, and I think it would help (me anyway) if this was merged -- Is that OK with you?

Hi @newville , yes, feel free to merge this. `read_specfile` function works,  even if #278 is not solved yet (GUI related).

**Comment by newville** [comment]
@maurov OK, great, I'll merge this

**Pull request merged**
