### PR TITLE
Adding Feff input generator from general structure files 

### PR DESCRIPTION
**Pull request by Ameyanagi**
Hi Matt,

I added a Feff input generator from the general structures we discussed on April 7th.
Can you give me feedback on whether this direction looks ok or if I should implement it in a different manner?
Please make a new branch if needed.

## Summary

- This PR adds a feature to generate FEFF input files from general structures supported by pymatgen.
- Main changes are the following. "structure2feff_browser.py" and "larch/xrd/structure2feff.py" were created to be consistent with "cif_browser.py" and "cif2feff.py" as much as possible.
  1. Added a new menu item in the "Feff" menu bar that opens a FEFF input generator.
  2. Added "[structure2feff_browser.py](https://github.com/Ameyanagi/xraylarch/compare/master...Ameyanagi:xraylarch:general-feff-input-generator?expand=1#diff-dfc3a80d03e047864ffbd1978d561c81946385884f1d3ac372a87cb9c8f58cbd)" that handles the GUI of the FEFF input generator.
  3. Added "[larch/xrd/structure2feff.py](https://github.com/Ameyanagi/xraylarch/compare/master...Ameyanagi:xraylarch:general-feff-input-generator?expand=1#diff-9e75acc47d47adf2a7f590906da47eef9f7ea05db62da0699b84329bfc22af5d)" that converts general structures to FEFF input files.
- For example, POSCAR from VASP, XYZ files, gjf files from Gaussian can be read by default functions of pymatgen. Other formats, such as mol2 files, supported by OpenBabel can also be read if OpenBabel is installed.

## Other Comments

- Tests have not been written, as I could not find tests for GUI.
- I created new functions as the current cif_browser.py highly depends on the CIF database that is implemented and is focused on parsing CIF files.

Ryuichi

### CODE REVIEW

**Comment by newville** [comment]
@Ameyanagi Wow, thanks!  I'll try to give a more thorough review in the next couple of days.

**Comment by newville** [comment]
@Ameyanagi This looks very good to me.  Would it be possible to include a small or medium-sized example structure file?

**Comment by Ameyanagi** [comment]
@newville Thanks, I will prepare some example structure files. Should I put it in /examples or in /tests?

**Comment by newville** [comment]
I would say to add it to the examples folder.

**Comment by Ameyanagi** [comment]
@newville I added several test files with different file formats (/structuredata/structure2feff). I used an organometallic cluster of mine as an example because it contains multiple metal centers, has crystalographic data, and is a molecule suitable for checking file format for molecules (such as XYZ and mol2).

Another issue is that I am unsure if the filename of poscar (VASP files) is usually saved as *.poscar or POSCAR. The file name "*.poscar" will work but "POSCAR" will not work on the current code, and this might need to be fixed if people prefer "POSCAR".

**Comment by newville** [comment]
@Ameyanagi  Great, thanks!  I think this will be very helpful, and merged it.

I have no opinion on POSCAR v poscar  - it would be nice if both worked, but we can deal with that.

I think that @maurov mentioned that "CIF to FDMNES" was being worked on (or was working).  We might want about refactoring/combining some of these codes to make more complete tools for "CIF or Structure Files" to "FEFF or FDMNES input", maybe both GUI and command-line / simple-ish functions....    But I'm not certain what that will look like. 

Anyway, thanks!

**Comment by Ameyanagi** [comment]
@newville Thank you for the merge. As for the filename, the suffix will work regardless of been capital or not. My concern was that it would not work if the filename were "POSCAR" with no file extensions.

I agree with the refactoring of the tools and am willing to help with that in the future.
Thanks.

**Comment by maurov** [comment]
@newville yes, we have a "CIF to FDMNES" code already available and I was planning to include it in Larch soon. The workflow is based on a Jupyter notebook.

**Pull request merged**
