### PR TITLE
Avoid WX non-US locales issue on Windows.

### PR DESCRIPTION
**Pull request by kbuc**
Add `ResetLocale()` to `wx.App` `OnInit()` to avoid error on MS Windows with non-US locales.
The error appears at least on Py >= 3.8 and Wx 4.1.1.

See for example wxWidgets/Phoenix#1751

### CODE REVIEW

**Comment by newville** [comment]
@kbuc thanks!  Others have definitely seen problems, and I'm slightly confused by all of this.   Like you say, it is specific to Python >= 3.8 and wxpython>=4.1.1 (or perhaps 4.1.0?).  

What I did between 0.9.53 release and now (which was reported to work) was to force setting the Locale to 'C' in `larch/apps.py` (https://github.com/xraypy/xraylarch/blob/41baadb635a66542ba22f7ce9c479116c1f93225/larch/apps.py#L55) and then call that before creating each app.   

I found that reading the wx docs on this was slightly confusing.  For example,  https://wxpython.org/Phoenix/docs/html/wx.App.html mentions the change but it also says that `ResetLocale()` is now a no-op and will be deprecated.   
It is then slightly confusing to be that adding that would do anything.   But if I remove my "set locale to C" hack and add that `ResetLocale` into `wxApp.OnInit()` as you have here, then I see that the locale is changed.  

But also (did I mention this confuses me?) it also seems like we could just add an `InitLocale` method to each of the apps (or maybe use a mixin class) that forces the locale to 'C' (aka `(None, None)`).    

My inclination is to merge this  (no harm in trying to fix this many ways) and then try over-writing `InitLocale`.  But if you're willing to try that, I'd say go for it.  Also: don't worry about the test failures.  That's all my fault and I will fix soon -- but I'd like to solve this and one other feature request and push out 0.9.54 in a few days.

**Comment by newville** [comment]
@kbuc will merge, and then may continue tweaking -- thanks very much!

**Comment by kbuc** [comment]
I agree that the issue is very confusing and the information sometimes contradicts.  Being "lucky" to have funny locale and being affected by the bug I can test different solutions. Installing 0.9.53 from the installer did not work out of the box.
I downgraded wxpython to 4.0.7, but no luck, until the `wxlib\__init__.py` contained

```python
import locale
locale.setlocale(locale.LC_ALL,'C')
```
and that was enough. (This was included in the 0.9.54dev)

However, to keep the latest WX 4.1.1, `self.ResetLocale()` was additionally neded in the `OnInit()`.

Perhaps a better solution is described here: https://discuss.wxpython.org/t/wxpython4-1-1-python3-8-locale-wxassertionerror/35168/3
I like the conditional part so that the reset is skipped in python 3.6-3.7. 

I'm not sure what causes this error, looks like PNG icon/image loading?

**Comment by newville** [comment]
@kbuc Thanks, I agree with all of that.  I do not understand how locales other than "None" or "C" can possibly work "correctly" on Windows with wxPython 4.1 and Python 3.8.   I also don't know where the real blame lies.    Sort of by definition, locale should be something that can be set at runtime, and maybe have a default set by the OS instance.   But to be able to set "C" locale, I think we need to add an InitLocale() workaround to all apps.   

Still trying to figure out the best workaround strategy.....

**Pull request merged**
