### PR TITLE
get list of motors used for scan, put at front of list of counters

### PR DESCRIPTION
**Pull request by newville**
Hi Mauro, how's this for better finding motor names from the spec/bliss files.  Basically, it pushes the 'counters' that are also motor names to the front of the list.   I think it's better, but maybe not perfect.  Thoughts?

### CODE REVIEW

**Comment by newville** [comment]
@maurov I'm going to merge, but if this is not yet good enough, let me know!

**Comment by maurov** [comment]
@newville thanks for looking into this, but I am afraid your change does not solve the problem with the correct selection of the X array in xas_viewer.

I propose to keep the `bytes2str` decoding and revert to previous by removing the `get_scan_motors` method. In fact, "motors" (= one value) and "counters" (= array) are not equivalent.

What I would like to achieve (not easy for me to dig into the Wx GUI part) is simply to choose as X array by default the one that is returned by the `get_scan_axis` method and keep in the combo box lists for the X and Y arrays selection those returned by `get_counters`.

If you could do this, it would be great, otherwise I will try doing it by myself and make a pull request. Please, let me know.

**Comment by newville** [comment]
@maurov  OK.  Yeah, the `bytes2str` thing seemed necessary to me.

Would it be OK to make sure "axis" from "get_scan_axis" is first in the list of arrays?    I think that will do what you want and seems to be better (if still not perfect). I just pushed that change, and let me know if that's better.

**Comment by maurov** [comment]
> Would it be OK to make sure "axis" from "get_scan_axis" is first in the list of arrays? I think that will do what you want and seems to be better (if still not perfect). I just pushed that change, and let me know if that's better.

OK, this seems to work, thanks!

Nevertheless, I have reached the following error at a certain point playing with the GUI (from the BLISS example file I sent, click on some `ascan`, including those with `xes_en` and then the `fscan`):

```bash
Traceback (most recent call last):
  File "/users/blissadm/local/xraylarch/larch/wxlib/specfile_importer.py", line 653, in onScanSelect
    self.set_energy_units()
  File "/users/blissadm/local/xraylarch/larch/wxlib/specfile_importer.py", line 594, in set_energy_units
    if xname.startswith('_index') or ix >= ncol:
UnboundLocalError: local variable 'ncol' referenced before assignment
```

I have not tried simply assigning `ncol = None` if the `try:` fails because actually it does not fail. Something going weird in the automatic keV->eV conversion.

**Comment by newville** [comment]
@maurov I see this too with one H5 BlissSpec scans that you sent. But for that, I see inconsistent data in the HDF5 file too:

```
>>> import h5py 
>>> p = h5py.File('ESRF_ID26-Fe2O3_0001.h5')
>>> p['68.1/measurement'].keys()
<KeysViewHDF5 ['I00', 'I00_raw', 'I01', 'I01_raw', 'I02', 'I02_bot', 'I02_bot_raw', 'I02_top', 'I02_top_raw', 'I04', 'I04_raw', 'I0t', 'I0t_raw', 'ICR', 'IF2', 'IF2_raw', 'IFt', 'IFt_raw', 'OCR', 'apd', 'det_dtc_ICR', 'det_dtc_apd', 'det_dtc_ketek', 'elapsed_time', 'hdh_angle', 'hdh_enc', 'hdh_enc_start', 'hdh_enc_stop', 'hdh_energy', 'ketek', 'mono_angle', 'mono_enc', 'mono_enc_start', 'mono_enc_stop', 'mono_energy', 'sec', 'tau', 'time_start', 'time_stop', 'wbvd_raw', 'zaptime']>
>>> p['68.1/measurement/I00'].shape
(17,)
>>> p['68.1/measurement/ketek'].shape
(20,)
>>> p['68.1/measurement/mono_enc'].shape
(12,)
>>> p['68.1/measurement/mono_energy'].shape
(12,)
>>> p['68.1/measurement/I0t'].shape
(17,)
>>> 

```

With an inconsistent number of measurement points (perhaps an aborted scan?), I think the array data is converted to an "object array" which is basically useless.  

Perhaps it is necessary to include a test in `get_scan()` of the number of points in each data array and select the smallest number -- perhaps that would salvage some of the data?

**Comment by maurov** [comment]
@newville good catch! OK, I put this test on the list of tasks.

**Pull request merged**
