### PR TITLE
Specfile improve and fixes

### PR DESCRIPTION
**Pull request by maurov**
@newville this is a draft pull request for fixing bugs and small improvements related to the Spec/BLISS importer. The goal is to get this feature more stable for the `0.9.53` release. I will push in this branch further in the coming days. Please, feel free to comment here if you see something weird or that you would like to change.

### CODE REVIEW

**Review by newville — APPROVED** [review]
I think this all looks good.   Since we don't have great tests for this, I would suggest merging early and testing ourselves.

**Comment by newville** [comment]
@maurov this all looks fine to me.  I'd be happy to merge if/when you think it is ready.

**Comment by newville** [comment]
@maurov Thanks!

**Comment by maurov** [comment]
@newville thanks for merging. I wanted to add some automatic tests, but it is not an easy task, so let's continue manually testing and fix bugs next.

**Pull request merged**
