### PR TITLE
adding example: Fe K-edge treatment in a Jupyter notebook

### PR DESCRIPTION
**Pull request by charlesll**
Following issue #324 :

Jupyter notebook example using xraylarch and lmfit in Python to treat spectra at the Fe K-edge.

Let me know if it's good for you!

### CODE REVIEW

**Comment by newville** [comment]
@charlesll Thanks - I have a couple of suggestions:

First, please use
```
    import larch
    from larch import Interpreter, Group
    from larch.xafs import autobk, xftf, mback,pre_edge, pre_edge_baseline
    from larch.io import read_ascii
```

instead of `from larch_plugins..... import ....`. - those modules aren't installed any more.

Second, the Fe data looks pretty spiky.  Is there better data to use?  

But also:  thanks!!  that looks very useful.

**Comment by charlesll** [comment]
@newville OK for the import

Which Fe data? The Ruffoni Fe foil or the melt? 

And thanks a lot for Larch, really really useful, it's a no-brainer particularly when there is a lot of data to treat. It has saved our life, for example to treat the 73 000 spectra recorded by a student recently... !

**Comment by newville** [comment]
@charlesll Hi Charles, I meant the Ruffino Fe foil data.  I guess it's fine to include, I just noticed the glitches...

**Comment by charlesll** [comment]
@newville OK, well we can replace it, no problem. Do you have a good spectrum? I searched on my computer but I don't have a really nice Fe K-edge spectrum of Fe, I only have quick scans for calibrating...

**Comment by newville** [comment]
@charlesll I think it is OK as is, but maybe consider using https://github.com/xraypy/xraylarch/blob/master/examples/xafsdata/fe.060 ?
Either is actually fine with me...

**Comment by charlesll** [comment]
@newville OK I used the file fe.060; I also moved the melt spectrum file to examples/xafsdata/, cleaned a bit the notebook and corrected some typos.

Let me know what you think!

**Comment by newville** [comment]
@charlesll Thanks, that looks really good, and adding the data to the example folder is a great idea.

I'll merge this - I think this will be really helpful to lots of people. Do you (and @maurov and @bruceravel ) think that having more examples like this in Jupyter notebooks would be helpful?

**Comment by charlesll** [comment]
@newville it appears that the EMG003 and Ruffoni Fe foil files were not deleted from the example/Jupyter folder, sorry. Do you want to delete them yourself or should I do another PR with the folder Jupyter cleaned from those files? Let me know.

Personally I like Jupyter notebook examples, so I am biased and my answer would be yes :) Then, of course, it depends on the examples you would like to show. For instance, on the machine learning / peak fitting side, it can be possible to show how Larch interacts with packages like scikit-learn, PyMC3 and so on.

**Comment by maurov** [comment]
> Personally I like Jupyter notebook examples, so I am biased and my answer would be yes :) Then, of course, it depends on the examples you would like to show. For instance, on the machine learning / peak fitting side, it can be possible to show how Larch interacts with packages like scikit-learn, PyMC3 and so on.

@charlesll thanks for adding this example of notebook, it will definetively be useful for others too. Please, if you want to share other notebooks, feel free to do it. If you use additional Python packages that are not coming with Larch, please, state it in the notebook.

> I'll merge this - I think this will be really helpful to lots of people. Do you (and @maurov and @bruceravel ) think that having more examples like this in Jupyter notebooks would be helpful?

 @newville yes, I think we should add more examples of notebooks in the Jupyter example folder. I will push soon a conda environment file in order to build a running Jupyter+Larch environment at  [mybinder.org](mybinder.org), this way anybody can run these example notebooks remotely.  We could also poll the Ifeffit community at the next Larch release about this.

If there is demand for it, I was thinking to add [sphinx-gallery](https://sphinx-gallery.github.io/stable/index.html) to the documentation and also make the standard plots of Larch available as pure Matplotlib or better Plotly based functions. What do you think?

**Comment by newville** [comment]
@maurov yes to using sphinx-gallery, and to more Jupyter-based examples.  And yes to using mybinder.org, though I don't know very much about doing that myself.

**Pull request merged**
