### PR TITLE
Athena group

### PR DESCRIPTION
**Pull request by maurov**
This pull request implements a simple utility for working with Athena project files in Larch (as library, not CLI), mainly targeted to Jupyter users, as recent requests (#264, and Ifeffit mailing list). Here what is introduced:

- Added HTML representation to `Group` showing attributes and types.
- Added `AthenaGroup`, a `Group` object exposing the  `groups` attribute to users (instead of the private `_athena_groups` dictionary). It has an HTML representation for showing the groups.
- A `sel` flag (0/1) is introduced as helper for indicating if a group is selected or not. It result useful for those users who want to loop over the groups.`
- The selection flag is shown in the HTML representation when  `AthenaGroup().show_sel = True` (default is False).
- ~~Added a Jupyter notebook UI for renaming or selecting groups in an `AthenaGroup` (requires `ipywidgets`).~~
- Added an example of notebook showing the usage.

@newville feel free to comment/modify or merge if you like it.

### CODE REVIEW

**Comment by newville** [comment]
@maurov  I'm OK with the `_repr_html_` method.  

I'm less sure about the IPython widgets, especially about them being *here*.   Maybe there should be a separate folder where the ipython widgets should be, with a dedicated "open Athena Project and select/rename datasets"  in ipython/jupyter?

**Comment by maurov** [comment]
@newville, the Jupyter UI for editing the name and selection of groups is removed now (PR description updated). I may create a separate module with a Jupyter UI in the future.

I have kept the `sel` attribute as helper for the users who want to loop over the groups, but it is not shown by default.

**Comment by newville** [comment]
@maurov  Thanks!  I think the "sel" flag is a fine idea.    I'll look into why this is failing tests (I suspect unrelated to the PR itself) and then hope to merge within a few days, that is if you're happy with it and no one else raises any objections.

**Comment by maurov** [comment]
@newville what about merging and closing this request?

**Comment by newville** [comment]
@maurov  ok, thanks for the reminder, merging now.

**Pull request merged**
